// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOxxWmZOXR-Vol5piGgo6DQpMwAIKNp8Y',
    appId: '1:1010840071708:web:cad358ba2c2cdad9a439d9',
    messagingSenderId: '1010840071708',
    projectId: 'classattendanceportal',
    authDomain: 'classattendanceportal.firebaseapp.com',
    storageBucket: 'classattendanceportal.firebasestorage.app',
    measurementId: 'G-RL09JQGMJR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGFW8UC0ilwwR1NvpnmhYvVz1SEHFFd1k',
    appId: '1:1010840071708:android:e7373eb01a03af4ea439d9',
    messagingSenderId: '1010840071708',
    projectId: 'classattendanceportal',
    storageBucket: 'classattendanceportal.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD47uyxLTpiWeEXoSm7L2BmFg5UBkWxQfM',
    appId: '1:1010840071708:ios:cfe683e92741b219a439d9',
    messagingSenderId: '1010840071708',
    projectId: 'classattendanceportal',
    storageBucket: 'classattendanceportal.firebasestorage.app',
    iosBundleId: 'com.example.classattendanceportal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOxxWmZOXR-Vol5piGgo6DQpMwAIKNp8Y',
    appId: '1:1010840071708:web:46686779797b34efa439d9',
    messagingSenderId: '1010840071708',
    projectId: 'classattendanceportal',
    authDomain: 'classattendanceportal.firebaseapp.com',
    storageBucket: 'classattendanceportal.firebasestorage.app',
    measurementId: 'G-053K22QC7B',
  );
}
